Repository ssuperpower-developer/SSU_STUDY, pull requests merged in 2022-05, with the labels that each got.

#33 OOP_4과제
  2-1_ObjectOrientedProgramming/HJH/OOP_4/Concert.java
  2-1_ObjectOrientedProgramming/HJH/OOP_4/DicApp .java
  2-1_ObjectOrientedProgramming/HJH/OOP_4/Grade .java
  2-1_ObjectOrientedProgramming/HJH/OOP_4/PhoneBook.java
  2-1_ObjectOrientedProgramming/HJH/OOP_4/Problem12.java
  2-1_ObjectOrientedProgramming/HJH/OOP_4/Rectangle.java
Labels: enhancement, help wanted, question

#34 Add OOP_4th workout
  2-1_ObjectOrientedProgramming/KHS/객체지향 4번째 과제/Dictionary.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 4번째 과제/Grade.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 4번째 과제/Num04.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 4번째 과제/Phonebook.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 4번째 과제/Programme.java
Labels: enhancement, help wanted

#32 Finish OOP Assignment No.3 (Chapter 4)
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question10.java
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question12A.java
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question12B.java
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question2.java
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question4.java
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question6.java
  2-1_ObjectOrientedProgramming/JWC/Assignment1/Question8.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Add.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question10.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question14.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question16.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question2.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question4.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question6.java
  2-1_ObjectOrientedProgramming/JWC/Assignment2/Question8.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question10.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question10/DicApp.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question10/Dictionary.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/CancelReservation.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/CheckReservation.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/DataBase.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/Main.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/MakeReservation.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question2.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question2/Grade.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question2/Question2.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question4.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question4/Question4.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question4/Rectangle.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question6.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question8.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question8/Phone.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question8/PhoneBook.java
Labels: enhancement, help wanted, question

#31 객체 과제
  2-1_ObjectOrientedProgramming/KSH/assignment3/Concert.java
  2-1_ObjectOrientedProgramming/KSH/assignment3/DicApp.java
  2-1_ObjectOrientedProgramming/KSH/assignment3/Grade.java
  2-1_ObjectOrientedProgramming/KSH/assignment3/PhoneBook.java
  2-1_ObjectOrientedProgramming/KSH/assignment3/Rectangle.java
Labels: enhancement

#35 OOP Chapter 4 Assignment Codes Refactoring
  2-1_DataStructure/JWC/Q3-3/.gitignore
  2-1_DataStructure/JWC/Q3-3/list.cpp
  2-1_DataStructure/JWC/Q3-3/list.h
  2-1_DataStructure/JWC/Q3-3/main.cpp
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/CancelReservation.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/DataBase.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/Main.java
  2-1_ObjectOrientedProgramming/JWC/Assignment3/Question12/MakeReservation.java
Labels: bug, enhancement, help wanted, question

#39 Finish OOP Assignment4
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question10/Dictionary.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question10/DictionaryApp.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question10/PairMap.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Circle.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Oval.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Question14.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Rect.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Shape.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question8/Point.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question8/PositivePoint.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question8/Question8.java
Labels: documentation, enhancement, question

#42 Add OOP_5th workout and Config files
  2-1_DataStructure/KHS/2번째 과제/20213118_2.cpp
  2-1_DataStructure/KHS/3번째 과제/main(succes).cpp
  2-1_DataStructure/KHS/3번째 과제/main.cpp
  2-1_DataStructure/KHS/과거/20213118.c
  2-1_DataStructure/KHS/과거/MagicSquare.cpp
  2-1_ObjectOrientedProgramming/KHS/객체지향 5번째 과제/PairMap.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 5번째 과제/Point.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 5번째 과제/Shape.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 5번째 과제/TV.java
  2-1_ObjectOrientedProgramming/KHS/객체지향 5번째 과제/test.java
Labels: question

#43 OOP 4번 과제 인터페이스 수정으로 인한 메소드 오버라이딩 재수정
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Circle.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Oval.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Rect.java
  2-1_ObjectOrientedProgramming/JWC/Assignment4/Question14/Shape.java
Labels: documentation, enhancement, question

#41 객체지향 과제
  2-1_ObjectOrientedProgramming/KSH/assignment4/Dictionary.java
  2-1_ObjectOrientedProgramming/KSH/assignment4/Main.java
  2-1_ObjectOrientedProgramming/KSH/assignment4/PositivePoint.java
Labels: bug, enhancement, help wanted, invalid, question
